### ISSUE TITLE
Rework/Remake the AI system

### ISSUE THREAD

**Issue by Shob3r** [funny-unity-game/Mission-Monkey#63] opened 2023-06-09 02:26 UTC
AI can't see the player if they are above/below and don't shoot if the player is too close to the AI

**Comment by ChakornK** [comment] 2023-06-13 03:03
AI not being able to shoot when too close to the player has been fixed in cda831f18d9f0fc7dbc7e8345fdc8e880f0076ed
It was caused by the AI movement speed being stopped when it was too close to the player, which meant it couldn't turn towards the player. Currently, the AI will push the player so in the future, a better solution needs to be added. But for now, it works. 

AI not being able to shoot the player if it is above or below the player has been fixed in 21e8dcf9038ce3d9aa6ee77c5a3d4eb450607153
This was fixed by modifying the bullet direction on the AiGlock script. Previously, the bullet would face the same direction as the enemy, which restricted its rotation on the local x-axis. Now, the bullet's direction is determined by the location of the player.

**Closed by ChakornK** 2023-06-13 03:03 UTC
Labels: bug
